name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [ opened, reopened, synchronize ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --release --verbose --features default

    - name: Check
      run: cargo test --verbose

    - name: Run tests
      run: cargo test --verbose

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Clippy
      run: cargo clippy \
            --all-features --all-targets --no-deps

    - name: Cargo fmt
      run: cargo fmt --check

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run tests
      run: cargo test --verbose --features default

  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run tests
      run: cargo doc --no-deps --features default